export const mockProducts = [
  {
    id: "1555798b-4c2d-4e13-bf26-fe08cda05784",
    batch_code: "VAL-ACEH-001",
    supplier_id: "sup-1",
    supplier_name: "Koperasi Nilam Aceh Barat",
    status: "VERIFIED",
    origin_village: "Pasi Mali",
    origin_district: "Woyla Barat",
    pa_percentage: 32.5,
    moisture: 2.1,
    available_volume_kg: 500,
    moq_kg: 50,
    price_per_kg: 850000,
    images: ["/images/premium_oil_dark.png"],
    tested_at: "2026-06-20T10:00:00Z",
    is_eudr: true
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    batch_code: "VLM-2606-002",
    supplier_id: "sup-2",
    supplier_name: "Tani Makmur Jaya",
    status: "VERIFIED",
    origin_village: "Pante Ceureumen",
    origin_district: "Pante Ceureumen",
    pa_percentage: 31.8,
    moisture: 2.8,
    available_volume_kg: 250,
    moq_kg: 50,
    price_per_kg: 830000,
    images: ["/images/premium_oil_dark.png"],
    tested_at: "2026-06-21T14:30:00Z",
    is_eudr: false
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    batch_code: "VLM-2606-003",
    supplier_id: "sup-3",
    supplier_name: "Koperasi Atsiri Gayo",
    status: "IN_LAB",
    origin_village: "Terangun",
    origin_district: "Gayo Lues",
    pa_percentage: 0,
    moisture: 0,
    available_volume_kg: 1000,
    moq_kg: 50,
    price_per_kg: 900000,
    images: ["/images/premium_oil_dark.png"],
    tested_at: null,
    is_eudr: false
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    batch_code: "VLM-2606-004",
    supplier_id: "sup-4",
    supplier_name: "Nilam Sejahtera Selatan",
    status: "VERIFIED",
    origin_village: "Kluet Utara",
    origin_district: "Aceh Selatan",
    pa_percentage: 34.2,
    moisture: 1.8,
    available_volume_kg: 150,
    moq_kg: 50,
    price_per_kg: 950000,
    images: ["/images/premium_oil_dark.png"],
    tested_at: "2026-06-18T09:15:00Z",
    is_eudr: true
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    batch_code: "VLM-2606-005",
    supplier_id: "sup-5",
    supplier_name: "Koperasi Tani Nusantara",
    status: "VERIFIED",
    origin_village: "Peudada",
    origin_district: "Bireuen",
    pa_percentage: 30.5,
    moisture: 3.0,
    available_volume_kg: 800,
    moq_kg: 50,
    price_per_kg: 800000,
    images: ["/images/premium_oil_dark.png"],
    tested_at: "2026-06-22T11:00:00Z"
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    batch_code: "VLM-2606-006",
    supplier_id: "sup-1",
    supplier_name: "Koperasi Nilam Aceh Barat",
    status: "DRAFT",
    origin_village: "Pasi Mali",
    origin_district: "Woyla Barat",
    pa_percentage: 0,
    moisture: 0,
    available_volume_kg: 300,
    moq_kg: 50,
    price_per_kg: 850000,
    images: ["/images/premium_oil_dark.png"],
    tested_at: null
  }
];

export const formatRupiah = (number: number) => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(number);
};
export const mockCircularProducts = [
  {
    id: '30000000-0000-0000-0000-000000000001',
    jenis: 'Kompos',
    nama: 'Organic Compost - Super Patchouli Residuals',
    mitra_pengolah_id: 'pt-limbah-nilam-berkah',
    mitra_pengolah_nama: 'PT Limbah Nilam Berkah',
    status: 'APPROVED',
    origin_district: 'Aceh Barat',
    stok_tersedia: 5000,
    min_order: 10,
    harga_per_unit: 2500,
    unit: 'Sack',
    images: ['/images/compost.png'],
    is_circular: true,
    category: 'Organic Compost',
    benefit: 'Meningkatkan kesuburan tanah secara organik dan alami untuk perkebunan kelapa sawit dan sayuran.',
    description: 'Kompos organik kualitas premium yang diproduksi dari fermentasi ampas daun dan batang nilam hasil penyulingan, diproses menggunakan dekomposer bio-aktif selama 30 hari.',
    sustainability_score: 5,
    sumber_batch_id: null,
    created_at: '2026-06-20T10:00:00Z'
  },
  {
    id: '30000000-0000-0000-0000-000000000002',
    jenis: 'Biochar',
    nama: 'Biochar Active Charcoal',
    mitra_pengolah_id: 'pt-limbah-nilam-berkah',
    mitra_pengolah_nama: 'PT Limbah Nilam Berkah',
    status: 'APPROVED',
    origin_district: 'Aceh Jaya',
    stok_tersedia: 3000,
    min_order: 5,
    harga_per_unit: 4500,
    unit: 'Sack',
    images: ['/images/biochar.png'],
    is_circular: true,
    category: 'Biochar',
    benefit: 'Memperbaiki aerasi tanah, menahan unsur hara dan air lebih lama dalam tanah berpasir.',
    description: 'Biochar karbon aktif tinggi hasil proses pirolisis lambat (slow pyrolysis) dari sisa ranting penyulingan minyak nilam pada suhu 450 derajat Celsius.',
    sustainability_score: 4,
    sumber_batch_id: null,
    created_at: '2026-06-21T14:30:00Z'
  },
  {
    id: '30000000-0000-0000-0000-000000000003',
    jenis: 'Hydrosol',
    nama: 'Patchouli Hydrosol Water Extract',
    mitra_pengolah_id: 'cv-sirkular-aceh',
    mitra_pengolah_nama: 'CV Sirkular Aceh',
    status: 'APPROVED',
    origin_district: 'Aceh Besar',
    stok_tersedia: 1500,
    min_order: 2,
    harga_per_unit: 15000,
    unit: 'Jerigen',
    images: ['/images/hydrosol.png'],
    is_circular: true,
    category: 'Patchouli Hydrosol',
    benefit: 'Bahan baku kosmetik alami, sabun organik, toner antiseptik, dan aromaterapi.',
    description: 'Air destilasi (hydrosol) murni dari proses penyulingan uap minyak nilam, mengandung sisa molekul minyak aktif dan aroma khas nilam yang menenangkan.',
    sustainability_score: 5,
    sumber_batch_id: null,
    created_at: '2026-06-22T11:00:00Z'
  }
];
